
[general]
	#The blocks whose hardness should be modified. This needs to be the registry name of the block followed by an @ followed by the new hardness, so for example: 'minecraft:stone@5'
	
	# Default MC hardness is 3 on all ores
	# Hardness is originally calculated based on pickaxe tier speed * 0.75 (gold ore is iron tier, pickaxe is x6, so 6 * 0.75 = 4.5)
	# Hardness gets rounded up or down on case basis
	# Iron gets a special incentive to make an iron pickaxe ASAP to increase mining speed
	# Obsidian gets nerfed a little bit
	
	tweak_hardness = [
	'geolosys:coal_ore@2',
	'geolosys:teallite_ore@3', 
	'geolosys:bauxite_ore@3', 
	'geolosys:cinnabar_ore@3', 
	'geolosys:malachite_ore@3',
	'geolosys:azurite_ore@3',
	'geolosys:hematite_ore@4',
	'tp:ender_ore@4',
	'geolosys:gold_ore@4', 
	'geolosys:lapis_ore@4', 
	'geolosys:platinum_ore@4', 
	'geolosys:platinum_ore@4',
	'geolosys:sphalerite_ore@4',
	'geolosys:galena_ore@4',
	'geolosys:kimberlite_ore@6',
	'geolosys:autunite_ore@6',
	'geolosys:beryl_ore@6', 
	'geolosys:quartz_ore@6',
	'minecraft:nether_quartz_ore@6',
	'minecraft:obsidian@18'
	]
	#The blocks whose mining level should be modified. This needs to be the registry name of the block followed by an @ followed by the tool class ('pickaxe', 'axe' or 'shovel') followed by an @ followed by the harvest level (0 = wood, 1 = stone, 2 = iron, 3 = diamond, custom levels work), so for example: 'minecraft:stone@pickaxe@2'

	# Note: Ores are added even if their harvest level doesn't change for clarity.
	
	tweak_mining_level = [
	'geolosys:coal_ore@pickaxe@0',
	'geolosys:teallite_ore@pickaxe@1', 
	'geolosys:bauxite_ore@pickaxe@1', 
	'geolosys:cinnabar_ore@pickaxe@1', 
	'geolosys:malachite_ore@pickaxe@1',
	'geolosys:azurite_ore@pickaxe@1',
	'geolosys:hematite_ore@pickaxe@1',
	'tp:ender_ore@pickaxe@2',
	'geolosys:gold_ore@pickaxe@2', 
	'geolosys:lapis_ore@pickaxe@2', 
	'geolosys:platinum_ore@pickaxe@2', 
	'geolosys:platinum_ore@pickaxe@2',
	'geolosys:sphalerite_ore@pickaxe@2',
	'geolosys:galena_ore@pickaxe@2',
	'geolosys:kimberlite_ore@pickaxe@2',
	'geolosys:autunite_ore@pickaxe@3',
	'geolosys:beryl_ore@pickaxe@3', 
	'geolosys:quartz_ore@pickaxe@3',
	'minecraft:nether_quartz_ore@pickaxe@3'
	]

