
#Factory manager config options
[factoryManager]
	#Maximum depth that the Factory Manager DFS algorithm should go
	#Range: > 0
	maxSearchDepth = 64
	#Number of ticks for the Factory Manager to rescan the network. Set to -1 to make it never rescan passively
	#Range: > -1
	rescanInterval = 100
	#Maximum number that the controller is allowed executes a single procedure in one execution pass
	#Extra attempts to the procedure will be ignored, and it's connection chain will stop
	#Range: 1 ~ 64
	repeatThreshold = 8

#Item intake config options
[itemIntake]
	#Interval between each pickup attempt for regular item intake, in ticks
	#Range: > 0
	regularPickupInterval = 80
	#Interval between each pickup attempt for instant item intake, in ticks
	#Range: > 0
	instantPickupInterval = 80
	#Maximum pickup radius that an item take can have, for regular item intake
	#Range: > 0
	regularMaxPickupDistance = 3
	#Maximum pickup radius that an item take can have, for instant item intake
	#Range: > 0
	instantMaxPickupDistance = 3
	#Internal inventory size for item intakes
	#Range: 1 ~ 27
	regularInventorySize = 5
	#Internal inventory size for instant item intakes
	#Range: 0 ~ 27
	instantInventorySize = 5

#Block property config options
[blocks]
	#Whether the redstone input block (sfm:redstone_input) is considered a cable
	isRedstoneInputBlockCables = false
	#Whether the redstone emitter block (sfm:redstone_emitter) is considered a cable
	isRedstoneEmitterBlockCables = false
	#Whether the block detector (sfm:bud) is considered a cable
	isBUDBlockCables = false
	#Whether the item intake block (sfm:item_intake) is considered a cable
	isItemIntakeBlockCables = false
	#Whether the instant item intake block (sfm:instant_item_intake) is considered a cable
	isInstantItemIntakeBlockCables = false

#Procedures config options
#Run '/sfm componentGroups reload' after updating config
[procedures]
	enableIntervalTrigger = true
	enableRedstoneTrigger = true
	enableBUDTrigger = true
	enableItemTransfer = true
	enableItemImport = true
	enableItemExport = true
	enableCrafting = true
	enableFluidTransfer = true
	enableRedstoneEmitter = true
	enableSignUpdater = true
	enableSequentialBranch = true
	enableMergeBranch = true
	enableFunctionHat = true
	enableFunctionInvoke = true

